### ISSUE TITLE
Mazin Saga Mutant Fighter Glitching

### ISSUE THREAD

**Issue by abelogan** [Project-Lunar/Project-Lunar-Issue-Tracker#10]
I have a rom with the same crc32 checksum as the one that's listed in the compatibility spreadsheeet as "Working", but every time I start it, the first enemy glitches into a brownish blob of pixels, and I can't damage him or move forward.

**Comment by DefKorns** [comment]
Hi @abelogan ,
Unfortunately that is related with the default emulator itself.

You can always leave a comment on the community [Compatibility List](https://docs.google.com/spreadsheets/d/1lW8ViyN_Sg0hrXCAqGgX0UEYwaWMhrcbJ_GzzNfTNlA).

So the games can be re-tested.

Thank you
