### ISSUE TITLE
games without sound

### ISSUE THREAD

**Issue by drewsquire** [Project-Lunar/Project-Lunar-Issue-Tracker#11]
I loaded some games and there was no sound:
Truxton
Verytex
Twin Hawk
Fireshark

**Comment by DefKorns** [comment]
Hi @drewsquire,
Unfortunately that is related with the default emulator itself.

You can always leave a comment on the community [Compatibility List](https://docs.google.com/spreadsheets/d/1lW8ViyN_Sg0hrXCAqGgX0UEYwaWMhrcbJ_GzzNfTNlA).

So the games cam be re-tested.

Thank you
