### ISSUE TITLE
Megadrive Asia - Crashes when using 6 button pad

### ISSUE THREAD

**Issue by phil99z** [Project-Lunar/Project-Lunar-Issue-Tracker#2]
I've managed to successfully install a bunch of roms to my Megadrive (Asian version).  When I use a normal 3 button pad (as supplied with my other UK spec Mini Megadrive) and power the system on it works fine but when I plug in my 6 button pad and power on the start up music glitches slightly and then the machine freezes.

This only happens when I power on with my 6 button pad plugged in.

**Comment by BananaRama203** [comment]
@phil99z can you please confirm what 6B this is? The stock 6B? can you also please explain what other peripherals you have connected and how you are powering the console?

**Comment by phil99z** [comment]
@swingflip its the stock/supplied 6 button pad that comes with the Asian Megadrive. Powered by a separate 5v PSU. No other peripherals plugged in and no cores for Retroarch/emulation station installed. Literally just PL and megadrive games accessed via the stick UI. 

I’ve since restored the device back to factory and reinstalled PL and started putting the games back on again with the 6 button pad plugged in and at the minute it seems fine. 

Only out a handful of roms on at the moment but will add more later (keeping under the 60 roms limit). Will see if it happens again. 

Keep up the good work guys - it’s hugely appreciated!
