### ISSUE TITLE
Rom Audio Missing Issue

### ISSUE THREAD

**Issue by ValionPride** [Project-Lunar/Project-Lunar-Issue-Tracker#3]
So far I have only run into issues with Teenage Mutant Ninja Turtles: Hyperstone Heist, the rom starts just fine, audio works during open vid seq, but once you hit start there is no audio at all, no music, not sfx.

**Comment by BananaRama203** [comment]
Hi, please refer to the FAQ, this rom has issues with the stock emulator. We are unable to fix this at this time as it requires someone to patch the rom to fix it.
