### ISSUE TITLE
NHL 95 - glitch with stock emulator(every shot is a backhander)

### ISSUE THREAD

**Issue by mwagner79** [Project-Lunar/Project-Lunar-Issue-Tracker#4]
Noticing that NHL 95 seems to have a glitch (using stock M2 emulator) where every shot is a "backhander".  Bizarre glitch to say the least, but wanted to report it since the official compatibility list had this one in green.

**Comment by DefKorns** [comment]
> That file is **read-only** and that wont change. if you have any game or report you think it should be there, please leave right click on the file and leave a comment.

Remember to include:
```
- rom name
- rom version
- rom crc32
```
you can check crc either with 7zip, rapidcrc or https://emn178.github.io/online-tools/crc32_checksum.html

Thats not a Project Lunar related issue. Report on the c[ompatibility list](https://docs.google.com/spreadsheets/d/1lW8ViyN_Sg0hrXCAqGgX0UEYwaWMhrcbJ_GzzNfTNlA)
